### ISSUE TITLE
Fix #10 luadoc / ldoc regressions

### ISSUE THREAD

**Issue by zm-cttae** [LuaLS/lua.tmbundle#11]
> ![image](https://user-images.githubusercontent.com/5213431/234162397-1b550d64-606c-4f03-a084-1e7f316d3947.png)
> 
> I did some tests and found some conflicts.  
> I'd like to view these as comments.
> 
> ![image](https://user-images.githubusercontent.com/5213431/234199841-040bc075-9805-42c3-8dc5-fbe623cfc3a8.png)
> 
> Wrong color with inline comments

Assigned to @zm-cttae.
Fix regressions introduced in #10 in rules for summary & documentation blocks.

**Comment by Hekili** [comment]
I have an issue that might relate to this ticket.

With lua-grammar disabled:

![image](https://user-images.githubusercontent.com/9438134/235252165-7a6dfaec-bfa9-4e26-88df-942f71a4014c.png)

With lua-grammar enabled:

![image](https://user-images.githubusercontent.com/9438134/235252234-cf922105-1546-4b17-9383-e169ffbb362c.png)

In the latter, the comment formatting (italics, dark grey text) bleeds past the closing `]]` for the multiline comment.

Moving the `]]` to a new line does not resolve it.

![image](https://user-images.githubusercontent.com/9438134/235252405-625ed549-9f58-4a6e-ad4e-4d36f5171831.png)

Closing the multiline comment with `--]]` resolves it.

![image](https://user-images.githubusercontent.com/9438134/235252491-7309ee29-4f57-4c3f-a3ab-60b657776561.png)

**Comment by zm-cttae** [comment]
I think the regex is unable to detect the boundary condition (closing block comment on this case) appropriately.

**Comment by sumneko** [comment]
![image](https://user-images.githubusercontent.com/5213431/236375404-dd6f651a-809d-4b39-a795-2bb6d54e203b.png)
It can be closed with a single `-` , maybe it is just a simple typo

**Comment by zm-cttae** [comment]
Will make fix PR today :)

**Comment by zm-cttae** [comment]
Fix confirmed in #13 - please merge!
