### ISSUE TITLE
Inline comment leak

### ISSUE THREAD

**Issue by sumneko** [LuaLS/lua.tmbundle#14]
![image](https://github.com/LuaLS/lua.tmbundle/assets/5213431/c102c389-fd2e-4525-b6cf-347ef512de0c)
![image](https://github.com/LuaLS/lua.tmbundle/assets/5213431/b30cf7df-2e8f-4427-91f2-8b3524e5c92d)
![image](https://github.com/LuaLS/lua.tmbundle/assets/5213431/9245e14a-5018-4f6c-985b-12ba19b48097)

```lua
print(1)
--[[ ]]
print(1)
```

**Comment by sumneko** [comment]
@zm-cttae

**Comment by zm-cttae** [comment]
_sighs in vs code without treesitter_
