### ISSUE TITLE
Local attributes look weird

### ISSUE THREAD

**Issue by Sainan** [LuaLS/lua.tmbundle#18]
Here's how they look with lua.tmbundle:
![image](https://github.com/LuaLS/lua.tmbundle/assets/63328889/0095e2c9-7b71-4d09-96a7-5c61b96d69b2)

And here's how they look with my own:
![image](https://github.com/LuaLS/lua.tmbundle/assets/63328889/316b199e-5f2b-463f-811b-2be1cfa3d485)

It's just as simple as this:
```XML
<dict>
	<key>match</key>
	<string>&lt;(const|close)&gt;</string>
	<key>name</key>
	<string>storage.type.attribute.lua</string>
</dict>
```

**Comment by sumneko** [comment]
Please make a pull request for it, thank you!

**Comment by Sainan** [comment]
I do not know how to make a .tmLanguage.json, I only work with .tmLanguage.
