### ISSUE TITLE
函数名写在前边时，不能语法高亮

### ISSUE THREAD

**Issue by Richard-Cat** [LuaLS/lua.tmbundle#4]
![image](https://user-images.githubusercontent.com/73878334/157592422-4e5cc185-a868-4cc3-b753-198faecaaa58.png)

**Comment by sumneko** [comment]
语法解析没法判断出你赋值的是一个函数，所以只能把这个函数名当做全局变量来着色。
你需要的是语义着色功能，这个是由语言服务提供的。

**Comment by Richard-Cat** [comment]
最近研究了下lua.tmLanguage.json，稍作修改，实现了函数名写在function前边时也着色

**Comment by Richard-Cat** [comment]
[lua.tmLanguage.json.txt](https://github.com/sumneko/lua.tmbundle/files/8666552/lua.tmLanguage.json.txt)

**Comment by Richard-Cat** [comment]
[lua.tmLanguage.json.txt](https://github.com/sumneko/lua.tmbundle/files/8666578/lua.tmLanguage.json.txt)

**Comment by sumneko** [comment]
你可以提个PR

**Comment by sumneko** [comment]
Fixed by #6
