### ISSUE TITLE
and和or没有高亮

### ISSUE THREAD

**Issue by CppCXY** [LuaLS/lua.tmbundle#5]
![{854A4440-2584-3A66-0D6E-02EF87EE3125}](https://user-images.githubusercontent.com/40318218/158925581-c87c9371-cd38-4565-8704-0867011a517d.jpg)

**Comment by sumneko** [comment]
![image](https://user-images.githubusercontent.com/5213431/158951318-f172eeef-6c61-4f23-8ba5-fd340878050a.png)
![image](https://user-images.githubusercontent.com/5213431/158951360-bb480d32-4797-4aba-9f0c-3b1f9e158559.png)

有高亮的，你的主题没给它分配颜色罢了。

**Comment by CppCXY** [comment]
![image](https://user-images.githubusercontent.com/40318218/158952300-c16aedb3-fb58-4042-b26e-c9128fdd7c08.png)
为什么注释颜色这么奇怪，类型不该绿色吗

**Comment by sumneko** [comment]
这里做准确匹配太麻烦了，直接用语义着色即可

**Comment by sumneko** [comment]
https://github.com/sumneko/lua.tmbundle/commit/bb18e8e236cc19ebbddcdc2bf17fb9a8a5a7a328
